### PR TITLE
Fix produt assigned to wrong user if save by shop manager

### LINKED ISSUE #1719: [Products]: Product is assigned to the shop manager when the shop manager publish a product drafted by the admin.
**Describe the bug**
When a `shop manager` is publishing a product that was drafted by an `admin`, the post author is changed to `shop manager` when Dokan is activated. But when only WooCommerce is there, the product is assigned to the `admin`.

**To Reproduce**
1. Create a draft product from an admin account.
2. Publish that product from a shop manager account.
3. The product will be assigned to the shop manager and not the admin.

**Expected behavior**
The product is supposed to be assigned to the admin when a shop manager has published the drafted product of an admin.

**Environment:**
- Dokan Version: [v3.7.0]
- WooCommerce Version: [v6.9.4]
- WordPress Version: [v6.0.2]

### PR DESCRIPTION
**Pull request by Aunshon**
### All Submissions:

* [x] My code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)
* [x] My code satisfies feature requirements
* [x] My code is tested
* [x] My code passes the PHPCS tests
* [x] My code has proper inline documentation
* [ ] I've included developer documentation (optional)
* [ ] I've added proper labels to this pull request

### Changes proposed in this Pull Request:

When a shop manager publishes a product drafted by admin that product author changed to that shop manager. now it is fixed.

Closes #1719

### How to test the changes in this Pull Request:

1. Create a product from admin and make it drafted. then publish that product by the shop manager. That product will be assigned to that shop manager, which means that the product author changes to shop manager which is unexpected.
2. This scenario also happens if the vendor is in-active and the admin or shop manager changes the product data.

### Changelog entry

Fix produt assigned to wrong user if save by shop manager

### PR Self Review Checklist:

* Code is not following code style guidelines
* Bad naming: make sure you would understand your code if you read it a few months from now.
* KISS: Keep it simple, Sweetie (not stupid!).
* DRY: Don't Repeat Yourself.
* Code that is not readable: too many nested 'if's are a bad sign.
* Performance issues
* Complicated constructions that need refactoring or comments: code should almost always be self-explanatory.
* Grammar errors.

### FOR PR REVIEWER ONLY:

> As a reviewer, your feedback should be focused on the idea, not the person. Seek to understand, be respectful, and focus on constructive dialog.

> As a contributor, your responsibility is to learn from suggestions and iterate your pull request should it be needed based on feedback. Seek to collaborate and produce the best possible contribution to the greater whole.

* [ ] Correct — Does the change do what it’s supposed to? ie: code 100% fulfilling the requirements?
* [ ] Secure — Would a nefarious party find some way to exploit this change? ie: everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities?
* [ ] Readable — Will your future self be able to understand this change months down the road?
* [ ] Elegant — Does the change fit aesthetically within the overall style and architecture?

### CODE REVIEW

File: includes/Assets.php [hunk 1]
```diff
@@ -121,9 +120,37 @@ public function enqueue_admin_scripts( $hook ) {
...
+    /**
+     * Load admin product localize data.
+     *
+     * @since DOKAN_SINCE
+     *
+     * @return array
+     */
+    public function admin_product_localize_scripts() {
+        return apply_filters(
+            'admin_product_localize_scripts', [
```
Comment (nurul-umbhiya) [inline includes/Assets.php:141]: use dokan prefix

**Review by nurul-umbhiya — APPROVED** [review]
