### PR TITLE
fix: iban, swift code number not showing in admin withdraw requests

### LINKED ISSUE #1134: Withdraw: IBAN number is not showing on the Dokan Admin
**Description of the Bug:**
When a Vendor makes a withdrawal request using Bank Transfer method, the IBAN Number is not showing on the **WordPress Dashboard > Dokan > Withdraw**
Screenshot URL: https://prnt.sc/10s5cz2

**How to Reproduce:**

1. Login as Vendor
2. Navigate to **Withdraw** and make and withdrawal request using **Bank Transfer**
3. Make sure the **IBAN** Number field is filled up from the **Vendor Dashboard > Settings > Payment**
4. Now login as an Admin
5. Navigate to **WordPress Dashboard > Dokan > Withdraw**
6. Check the **Details** column and you will see that the **IBAN** Number is not there. 

**Expected Behavior:**
The **Details** column should show the **IBAN** number as well since this is required to make Bank Transfer in some European Countries. 

**System Status:**
Dokan Lite: 3.2.3
Dokan Pro: 3.2.1
WordPress: 5.7

### PR DESCRIPTION
**Pull request by kapilpaul**
This PR will fix the issue of not showing IBAN Number, Swift Code in admin withdraw request details.

closes #1134

Final Output:

Screenshot at Mar 24 10-45-00

### CODE REVIEW

File: src/admin/pages/Withdraw.vue [hunk 1]
```diff
@@ -337,19 +337,27 @@ export default {
 
                 } else if ( 'bank' === method ) {
                     if ( data.bank.hasOwnProperty('ac_name') ) {
-                        details = this.sprintf( this.__( 'Account Name: %s', 'dokan-lite' ),  data.bank.ac_name );
+                        details = this.sprintf( this.__( '<p>Account Name: %s</p>', 'dokan-lite' ),  data.bank.ac_name );
```
Comment (nurul-umbhiya) [inline src/admin/pages/Withdraw.vue:340]: html tags in translatable string will throw js error for some languages, kindly remove p tags from all translatable strings

**Review by nurul-umbhiya — APPROVED** [review]
