### PR TITLE
fix: Unable to add multiple lines to the Short Description field issu…

### LINKED ISSUE #1167: Products: Unable to add multiple lines to the Short Description field.
**Description of the Bug:**
Vendors are unable to add multiple lines on the Add New Product form (popup/non-popup) Short Description field.

Screenshots: 
https://snipboard.io/l0SnIg.jpg
https://snipboard.io/gLoFHU.jpg

**How to reproduce:**
- Add a new product from the vendor dashboard
- Try to add multiple lines in the short description field
- It doesn't work

**Expected Behavior:**
Vendors should be able to add multiple lines on the Add New Product (popup/non-popup) form Short Description field.

**System Status:**
Dokan Lite: 3.2.4
Dokan Pro: 3.2.2
WordPress: 5.7
WooCommerce: 5.1.0

### PR DESCRIPTION
**Pull request by alamgircsebd**
…e fixed #1167

### CODE REVIEW

File: assets/src/js/store-lists.js [hunk 1]
```diff
@@ -71,13 +71,15 @@
...
 
-            $('body').keypress(function (e) {
-                var key = e.which;
-                if( key == 13 ) {
-                    $( "#dokan-store-listing-filter-form-wrap" ).submit();
-                    return false;  
-                }
-            }); 
+            if ( $( "#dokan-store-listing-filter-form-wrap" ).length ) {
+                $('body').keypress(function (e) {
```
Comment (shohag121) [inline assets/src/js/store-lists.js:75]: Please add event delegation.

**Review by shohag121 — CHANGES_REQUESTED** [review]

**Review by shohag121 — APPROVED** [review]
