### PR TITLE
Fix/multiple issues

### LINKED ISSUE #1773: Vendor email address is not showing up on the store header.
**Describe the bug**
The email address for vendors is not showing up on the store header even after having it enabled from the Vendor dashboard > Store > Settings section [[screenshot](https://snipboard.io/UMR2pW.jpg)] and **not hidden** from the WP admin dashboard > Dokan > Settings > Appearance screen [[screenshot](https://snipboard.io/ECNdmJ.jpg)].

**How to reproduce**

- Enable the setting to display vendor email address from Vendor dashboard > Store > Settings section
- Make sure that the vendor email address is not hidden from the WP admin dashboard > Dokan > Settings > Appearance screen

**Expected behavior**
The email address should be visible on the store header when it is enabled by the vendor and not disabled by the site admin.

**Environment**
Dokan: v3.7.7
WordPress: v6.1.1
WooCommerce: v7.1.0

### PR DESCRIPTION
**Pull request by tanjiralmamun**
### All Submissions:

* [x] My code follows the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)
* [x] My code satisfies feature requirements
* [x] My code is tested
* [ ] My code passes the PHPCS tests
* [ ] My code has proper inline documentation
* [ ] I've included developer documentation (optional)
* [ ] I've added proper labels to this pull request

### Changes proposed in this Pull Request:

1. Closes #1773.
2. `Enhancement` last-page and first-page icon inconsistency (https://snipboard.io/XkgVvA.jpg)
3. `Enhancement` Adjusted store banner image stretching issue (https://snipboard.io/iMNATa.jpg)

### How to test the changes in this Pull Request:

1.
4.
5.

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### PR Self Review Checklist:

* Code is not following code style guidelines
* Bad naming: make sure you would understand your code if you read it a few months from now.
* KISS: Keep it simple, Sweetie (not stupid!).
* DRY: Don't Repeat Yourself.
* Code that is not readable: too many nested 'if's are a bad sign.
* Performance issues
* Complicated constructions that need refactoring or comments: code should almost always be self-explanatory.
* Grammar errors.

### FOR PR REVIEWER ONLY:

> As a reviewer, your feedback should be focused on the idea, not the person. Seek to understand, be respectful, and focus on constructive dialog.

> As a contributor, your responsibility is to learn from suggestions and iterate your pull request should it be needed based on feedback. Seek to collaborate and produce the best possible contribution to the greater whole.

* [ ] Correct — Does the change do what it’s supposed to? ie: code 100% fulfilling the requirements?
* [ ] Secure — Would a nefarious party find some way to exploit this change? ie: everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities?
* [ ] Readable — Will your future self be able to understand this change months down the road?
* [ ] Elegant — Does the change fit aesthetically within the overall style and architecture?

### CODE REVIEW

File: templates/store-header.php [hunk 1]
```diff
@@ -83,7 +83,7 @@ class="profile-info-img">
                                 </li>
                             <?php } ?>
 
-                            <?php if ( ! dokan_is_vendor_info_hidden( 'email' ) && $store_user->show_email() === 'yes' ) { ?>
+                            <?php if ( ! dokan_is_vendor_info_hidden( 'email' ) && $store_user->show_email() == 'yes' ) { ?>
```
Comment (nurul-umbhiya) [inline templates/store-header.php:86]: this fix won't work. kindly rewrite this as below:
```
<?php if ( ! dokan_is_vendor_info_hidden( 'email' ) && $store_user->show_email() ) { ?>
```
note: show_email() method will return boolean value

Comment (tanjiralmamun) [reply templates/store-header.php]: Done

**Review by nurul-umbhiya — APPROVED** [review]
