### PR TITLE
subscription product category fix

### LINKED ISSUE #1662: [Products]: The new category selection pop-up of the add new product page is not mobile responsive.
**Describe the bug**
The newly added product category selection pop-up is not mobile responsive on the `add new product` page and the `edit product` page.

**To Reproduce**
1. Navigate to the vendor dashboard on a mobile phone.
2. Visit the add new product section and open the category selection pop-up.
3. The same issue lies in the edit product page also.

**Expected behavior**
It would be nice to have a more convenient UI for mobile view.

**Screenshots**
https://snipboard.io/ckbh8J.jpg

**Environment:**
 - Dokan Version: [v3.6.3]
 - Dokan Pro Version: [v3.7.3]
 - WooCommerce Version: [v6.7.0]

### PR DESCRIPTION
**Pull request by Aunshon**
### All Submissions:

* [x] My code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)
* [x] My code satisfies feature requirements
* [x] My code is tested
* [x] My code passes the PHPCS tests
* [x] My code has proper inline documentation
* [ ] I've included developer documentation (optional)
* [x] I've added proper labels to this pull request

### Changes proposed in this Pull Request:

Closes #1662
Closes https://github.com/weDevsOfficial/dokan-pro/issues/1963

Dokan Pro PR: https://github.com/weDevsOfficial/dokan-pro/pull/1969

### How to test the changes in this Pull Request:

1. Create a Dokan subscription product with some category restriction on it, subscribe to a vendor on it, and try to add a product in a category you will see only the restricted category will show.
2. When you restrict categories you will only top-level categories.
3. Check responsive design in the multi-step category in the vendor dashboard.

### Changelog entry

- **Fix:** Categories when restrict categories from vendor subscription module.
- **Fix:** Responsive mobile version in category UI.

### PR Self Review Checklist:

* Code is not following code style guidelines
* Bad naming: make sure you would understand your code if you read it a few months from now.
* KISS: Keep it simple, Sweetie (not stupid!).
* DRY: Don't Repeat Yourself.
* Code that is not readable: too many nested 'if's are a bad sign.
* Performance issues
* Complicated constructions that need refactoring or comments: code should almost always be self-explanatory.
* Grammar errors.

### FOR PR REVIEWER ONLY:

> As a reviewer, your feedback should be focused on the idea, not the person. Seek to understand, be respectful, and focus on constructive dialog.

> As a contributor, your responsibility is to learn from suggestions and iterate your pull request should it be needed based on feedback. Seek to collaborate and produce the best possible contribution to the greater whole.

* [ ] Correct — Does the change do what it’s supposed to? ie: code 100% fulfilling the requirements?
* [ ] Secure — Would a nefarious party find some way to exploit this change? ie: everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities?
* [ ] Readable — Will your future self be able to understand this change months down the road?
* [ ] Elegant — Does the change fit aesthetically within the overall style and architecture?

### CODE REVIEW

File: includes/Upgrade/Upgrades/V_3_6_3.php [hunk 1]
```diff
@@ -0,0 +1,47 @@
+<?php
```
Comment (nurul-umbhiya) [inline includes/Upgrade/Upgrades/V_3_6_3.php:1]: move this upgrader to Dokan Pro

File: includes/Upgrade/Upgrades/V_3_6_3.php [hunk 2]
```diff
@@ -0,0 +1,47 @@
...
+            'return' => 'ids',
+            'limit'  => -1,
+        ];
+
+        $products = wc_get_products( $args );
+        $dokan_category = new Categories();
+        $all_categories = $dokan_category->get_all_categories( true );
+
+        foreach ( $products as $product_id ) {
+            $categories = get_post_meta( $product_id, '_vendor_allowed_categories', true );
```
Comment (nurul-umbhiya) [inline includes/Upgrade/Upgrades/V_3_6_3.php:30]: priority will be vendor user meta, then post meta, so I think we need to rethink this approach

File: includes/Upgrade/Upgrades/V_3_6_3.php [hunk 3]
```diff
@@ -0,0 +1,47 @@
...
+
+            if ( ! empty( $categories ) && is_array( $categories ) ) {
+                foreach ( $categories as $cat_index => $category_id ) {
+                    if( 0 !== intval( $all_categories[ $category_id]['parent_id'] ) ) {
```
Comment (nurul-umbhiya) [inline includes/Upgrade/Upgrades/V_3_6_3.php:34]: fix all the phpcs related issues

**Review by nurul-umbhiya — APPROVED** [review]
