### PR TITLE
Fix/vendor store per page placeholder

### LINKED ISSUE #1375: From the Vendor Dashboard > Settings page, Store Products Per Page place holder text needs enhancement
Description:

Products Per Page on the **Vendor Dashboard > Settings** page, if there's no value set on the field then users see 10 which leads to confusion. 

The placeholder text should be modified to avoid confusion. There can be a string saying "Enter the number products" as the placeholder text on that field.

System Status:

Dokan Lite v3.2.14
Dokan Pro v3.3.8

### PR DESCRIPTION
**Pull request by rajankarmakar**
There was an issue on the vendor settings page. On the Store Products Per Page setting field the placeholder was hardcoded with the number 10. Which is confusing for vendors to understand.

fix #1375

### CODE REVIEW

**Review by SadikurSadik — APPROVED** [review]

File: templates/settings/store-form.php [hunk 1]
```diff
@@ -125,7 +125,7 @@
             <label class="dokan-w3 dokan-control-label" for="dokan_store_ppp"><?php esc_html_e( 'Store Products Per Page', 'dokan-lite' ); ?></label>
 
             <div class="dokan-w5 dokan-text-left">
-                <input id="dokan_store_ppp" value="<?php echo esc_attr( $store_ppp ); ?>" name="dokan_store_ppp" placeholder="10" class="dokan-form-control" type="number">
+                <input id="dokan_store_ppp" value="<?php ! empty( $store_ppp ) ? esc_attr_e( $store_ppp, 'dokan-lite' ) : ''; ?>" name="dokan_store_ppp" placeholder="<?php esc_attr_e( 'Enter the number of products', 'dokan-lite' ); ?>" class="dokan-form-control" type="number">
```
Comment (alamgircsebd) [inline templates/settings/store-form.php:128]: here no need to use localization `esc_attr_e( $store_ppp, 'dokan-lite' )`

**Review by alamgircsebd — CHANGES_REQUESTED** [review]

**Review by alamgircsebd — APPROVED** [review]

File: templates/settings/store-form.php [hunk 2]
```diff
@@ -125,7 +125,7 @@
             <label class="dokan-w3 dokan-control-label" for="dokan_store_ppp"><?php esc_html_e( 'Store Products Per Page', 'dokan-lite' ); ?></label>
 
             <div class="dokan-w5 dokan-text-left">
-                <input id="dokan_store_ppp" value="<?php echo esc_attr( $store_ppp ); ?>" name="dokan_store_ppp" placeholder="10" class="dokan-form-control" type="number">
+                <input id="dokan_store_ppp" value="<?php ! empty( $store_ppp ) ? esc_attr( $store_ppp ) : ''; ?>" name="dokan_store_ppp" placeholder="<?php esc_attr_e( 'Enter the number of products', 'dokan-lite' ); ?>" class="dokan-form-control" type="number">
```
Comment (nurul-umbhiya) [inline templates/settings/store-form.php:128]: change placeholder text

Comment (nurul-umbhiya) [reply templates/settings/store-form.php:128]: Number of products to display  on store page

**Review by nurul-umbhiya — APPROVED** [review]
