### PR TITLE
fix: guest checkout name in vendor order details fixed #894

### LINKED ISSUE #894: Guest Checkout name on the vendor order
Description : 

If you enable guest check checkout Dokan vendor order shows guest while the WooCommerce shows the user name

Expected behavior

Dokan should show the user name the same as WooComerce does 

Screenshots : 

https://nimb.ws/hEWenJ
https://nimb.ws/szZl0Q

### PR DESCRIPTION
**Pull request by kapilpaul**

### CODE REVIEW

File: templates/orders/listing.php [hunk 1]
```diff
@@ -103,7 +103,7 @@
                                 }
 
                             } else {
-                                $user = __( 'Guest', 'dokan-lite' );
+                                $user = __( $order->get_formatted_billing_full_name(), 'dokan-lite' );
```
Comment (sabbir1991) [inline templates/orders/listing.php:106]: Remove translation function from vaiable
