### PR TITLE
Show multistep categories as language selected by wpml

### LINKED ISSUE #1669: [Dokan WPML]: All the categories are being shown when the dashboard is being viewed in second language.
**Describe the bug**
All the categories (Translate and base language categories) are being shown on the add product page's categories section.

**Steps to reproduce the behavior:**
1. Install and activate WPML and Dokan WPML integration.
2. Keep at least two languages on the site. For example, English (base) and Bengali.
3. Translate the vendor dashboard and all the taxonomies (only categories) of the site.
4. View the vendor dashboard in the second language that you translated the site.
5. On the category selection UI all the categories will appear both in English and Bengali as shown in [this screenshot](https://snipboard.io/Vxpjnb.jpg).

**Expected behavior**
When the vendor dashboard is viewed in Bengali, only the categories that are translated into Bengali should appear.

**Screenshots**
https://snipboard.io/Vxpjnb.jpg

**Environment:**
 - Dokan Version: [v3.6.3]
 - WooCommerce Version: [v6.7.0]

### PR DESCRIPTION
**Pull request by Aunshon**
### All Submissions:

* [x] My code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)
* [x] My code satisfies feature requirements
* [x] My code is tested
* [x] My code passes the PHPCS tests
* [x] My code has proper inline documentation
* [ ] I've included developer documentation (optional)
* [x] I've added proper labels to this pull request

### Changes proposed in this Pull Request:

Closes #1669

### How to test the changes in this Pull Request:

1. Install WPML and check if the multistep categories are shown as the selected language, should not show all language categories.

### Changelog entry

> Fix: wpml support in the multistep product category.

### PR Self Review Checklist:

* Code is not following code style guidelines
* Bad naming: make sure you would understand your code if you read it a few months from now.
* KISS: Keep it simple, Sweetie (not stupid!).
* DRY: Don't Repeat Yourself.
* Code that is not readable: too many nested 'if's are a bad sign.
* Performance issues
* Complicated constructions that need refactoring or comments: code should almost always be self-explanatory.
* Grammar errors.

### FOR PR REVIEWER ONLY:

> As a reviewer, your feedback should be focused on the idea, not the person. Seek to understand, be respectful, and focus on constructive dialog.

> As a contributor, your responsibility is to learn from suggestions and iterate your pull request should it be needed based on feedback. Seek to collaborate and produce the best possible contribution to the greater whole.

* [ ] Correct — Does the change do what it’s supposed to? ie: code 100% fulfilling the requirements?
* [ ] Secure — Would a nefarious party find some way to exploit this change? ie: everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities?
* [ ] Readable — Will your future self be able to understand this change months down the road?
* [ ] Elegant — Does the change fit aesthetically within the overall style and architecture?

### CODE REVIEW

File: includes/ProductCategory/Categories.php [hunk 1]
```diff
@@ -129,13 +129,26 @@ private function get_categories() {
         global $wpdb;
 
         // get all categories
+        $table  = $wpdb->prefix . 'terms';
+        $fields = 'terms.term_id, terms.name, tax.parent AS parent_id';
+        $join   = "INNER JOIN `{$wpdb->prefix}term_taxonomy` AS tax ON terms.term_id = tax.term_id";
+        $where  = " AND tax.taxonomy = 'product_cat'";
+
+        $wpml_exists      = function_exists( 'wpml_get_current_language' );
+        $current_language = apply_filters( 'wpml_current_language', null );
```
Comment (nurul-umbhiya) [inline includes/ProductCategory/Categories.php:138]: use `wpml_get_current_language()` instead of apply_filters( 'wpml_current_language', null );

**Review by nurul-umbhiya — APPROVED** [review]
