### PR TITLE
fix: restore order stock if its been reduced by twice is fixed #428

### LINKED ISSUE #428: In sub order, stock status is not getting correctly deducted
In suborders, each product stock gets deducted by 2 although the sold individually option is checked from product edit page

video: https://www.useloom.com/share/cbde60426cee4aebb855d80c5e2b185b

### PR DESCRIPTION
**Pull request by saimonh3**

### CODE REVIEW

File: includes/class-order-manager.php [hunk 1]
```diff
@@ -478,4 +481,48 @@ public function ensure_vendor_coupon( $valid, $coupon ) {
...
+            if ( ! $item_stock_reduced || ! $product || ! $product->managing_stock() ) {
+                continue;
+            }
+
+            $item_name = $product->get_formatted_name();
+            $new_stock = wc_update_product_stock( $product, $item_stock_reduced, 'increase' );
+
+            if ( is_wp_error( $new_stock ) ) {
+                /* translators: %s item name. */
+                $order->add_order_note( sprintf( __( 'Unable to restore stock for item %s.', 'woocommerce' ), $item_name ) );
```
Comment (sabbir1991) [inline includes/class-order-manager.php]: Change text domain `woocommerce`
